### PR TITLE
Novus 10G and 100G

### PR DESCRIPTION
**Pull request by alakendu**
This will address #155 #160 and #161

### CODE REVIEW

**Comment by alakendu** [comment]
I am trying to fix probable use case for Novus10G and Novus100G load module without interrupting existing code block. I feel still their are scope of improvement and overcome collateral. Please review this pull request.

**Review by ajbalogh — APPROVED** [review]

**Comment by ANISH-GOTTAPU** [comment]
Hi Alakendu,

The media type is not set to fiber and always defaults to copper for 10G card with the updated code

Please find the test attached to verify 

[test_layer1_speed_Novus_10G.zip](https://github.com/open-traffic-generator/ixnetwork/files/5714424/test_layer1_speed_Novus_10G.zip)

**Comment by ANISH-GOTTAPU** [comment]
@alakendu 

For 100G Novus, 
1) updating two ports from 100G-40G or vice versa is taking nearly 4 minutes, not sure this can be optimized as the RG is updating.
2) updating two ports from same speed to same speed is taking 2 minutes, I feel this can be optimized by checking the location and speed and don't do any operation at port level. You can put a thought to it

**Comment by ANISH-GOTTAPU** [comment]
@alakendu : If I am running the script `test_layer1_speed_Novus_10G.py` of PR #194 auto negotiation is not applied. If I run separately for 10G it is working but not working if i execute in loop with different speeds. please check once

**Review by ashutshkumr — APPROVED** [review]
There are other outstanding issues that will be fixed in separate PRs. Merging this for now since changes look good and there wasn't any collateral reported.

**Pull request merged**
