### PR TITLE
Include changes from stabilize

### PR DESCRIPTION
**Pull request by ashutshkumr**
## Summary of changes:
- Introduced `tests/utils` to refactor planned tests (be able to validate stats and capture for each relevant test)
- Added planned tests - WIP
- Added GTPv1 header - WIP
- Fixed issue with missing/broken stat attributes - https://github.com/open-traffic-generator/ixnetwork/issues/72
- Fixed issue with incorrect pcap received intermittently - https://github.com/open-traffic-generator/ixnetwork/issues/75
- Fixed issue with l1 speed not being set for VM ports- https://github.com/open-traffic-generator/ixnetwork/issues/73
- Added requirements.txt to record pre-build dependencies
- Added steps for dev setup in contributing.md
- Modify publish.yml to prepare setup for running tests per changes above
- Expose `tests/settings.json` to allow directly configuring it (and other config files specific to linting and pytest)
- Modify README.md to include working code and correct formatting

## Things to note during merge:
- Upgrade version and run tests against newly published package (to check for any regression)

### CODE REVIEW

**Review by ajbalogh — APPROVED** [review]
All ci/cd steps have passed.
I don't agree with not using pandas.
We should be steering customers to best practices and an independent utils/common files is not the best approach.
We should be providing an approach that is based on pytest of which fixtures are central feature versus a custom utility library.
If the models are changed we should align with the models (ie port stats, flow stats).

**Review by winstonliu1111 — APPROVED** [review]
LGTM

**Comment by ashutshkumr** [comment]
> All ci/cd steps have passed.
> I don't agree with not using pandas.
> We should be steering customers to best practices and an independent utils/common files is not the best approach.
> We should be providing an approach that is based on pytest of which fixtures are central feature versus a custom utility library.
> If the models are changed we should align with the models (ie port stats, flow stats).

I agree with moving most (relevant) utils items to fixtures, and will track it as seperate issue (if that's ok).
We can't completely retire utils yet though because currently it is helping us with rapid migrations without needing to batch update test scripts.

Regarding `pandas`, I have nothing against it and it's a great library for working with different datasets.
I just removed it from readme sample because equivalent code using `in-built` seemed more concise and intuitive. i.e.

```python
request = result.PortRequest(column_names=['name', 'location', 'frames_tx', 'frames_rx'])
results = api.get_port_results(request)

# pandas
df = pandas.DataFrame.from_dict(results)
df.frames_tx.sum()

# in-built
sum(r['frames_tx'] for r in results)
```

**Review by ankur-sheth — APPROVED** [review]

**Comment by winstonliu1111** [comment]
regarding andy/ashutosh's comment on pandas, I think pandas is super useful for slice/dice and when you deal with a table.  the in-built mechanism sort of breaks down and efficiency when you have to access more than 1 metric, or perform different operations over the same metric.  maybe show both ways?  and show pandas where that really shines.

**Pull request merged**
