### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by alakendu**

### CODE REVIEW

**Comment by ashutshkumr** [comment]
@ajbalogh kindly hold on from merging this until we gather more data on failures. This change may cause change in some test expectations.

Last successful pipeline on master: https://github.com/open-traffic-generator/ixnetwork/actions/runs/408243579

**Comment by ajbalogh** [comment]
Hi @ashutshkumr  - that was by accident - I will leave the merge to you :)

**Comment by alakendu** [comment]
All test cases are passing with this fix as well as handling original  issue #108 . Please review

**Review by ajbalogh — APPROVED** [review]

**Review by ashutshkumr — APPROVED** [review]
@ajbalogh mix of all e2e and unit tests (run locally) passed as well. There's been more changes in how we set fields not provided by user.

Could you please review those ?

**Pull request merged**
